version: '3.8'

services:
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo_container'
    ports:
      - '27017:27017'

  mysql:
    image: 'mysql:latest'
    container_name: 'mysql_container'
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_USER=user'
      - 'MYSQL_PASSWORD=password'

volumes:
  mysql_data:
